use super::Generator;
use crate::frontend::ast::{BaseType, Field, State, TytoProgram, TytoType};

pub struct JavaGenerator;

fn to_camel_case(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

fn to_java_type(ty: &TytoType) -> String {
    match ty {
        TytoType::Base(BaseType::String) => "String".to_string(),
        TytoType::Base(BaseType::Int) => "Integer".to_string(),
        TytoType::Base(BaseType::Float) => "Double".to_string(),
        TytoType::Base(BaseType::Bool) => "Boolean".to_string(),
        TytoType::Array(inner) => format!("java.util.List<{}>", to_java_type(inner)),
        TytoType::Optional(inner) => format!("java.util.Optional<{}>", to_java_type(inner)),
    }
}

fn get_state_fields(program: &TytoProgram, state: &State) -> Vec<Field> {
    let mut fields = Vec::new();
    if let Some(ctx) = &program.context {
        fields.extend(ctx.fields.clone());
    }
    if let Some(data) = &state.data {
        fields.extend(data.fields.clone());
    }
    fields
}

impl Generator for JavaGenerator {
    fn extension(&self) -> &'static str {
        "java" 
    }

    fn generate(&self, program: &TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("// Automatically generated by Tyto\n");
        output.push_str("// Do not edit this file manually.\n\n");

        let state_names: Vec<String> = program
            .states
            .iter()
            .map(|s| format!("{}State", s.name))
            .collect();

        output.push_str(&format!(
            "sealed interface TytoState permits {} {{}}\n\n",
            state_names.join(", ")
        ));

        for state in &program.states {
            let fields = get_state_fields(program, state);

            let mut fields_str = Vec::new();
            for field in &fields {
                fields_str.push(format!(
                    "{} {}",
                    to_java_type(&field.field_type),
                    field.name
                ));
            }

            output.push_str(&format!(
                "record {}State({}) implements TytoState {{\n",
                state.name,
                fields_str.join(", ")
            ));

            let source_fields = get_state_fields(program, state);

            for transition in &state.transitions {
                let target_state = program
                    .states
                    .iter()
                    .find(|s| s.name == transition.target)
                    .expect("Error: Target state not found.");

                let target_fields = get_state_fields(program, target_state);

                let mut new_fields = Vec::new();
                for t_field in &target_fields {
                    if !source_fields
                        .iter()
                        .any(|s_field| s_field.name == t_field.name)
                    {
                        new_fields.push(t_field.clone());
                    }
                }

                let mut args = Vec::new();
                for f in &new_fields {
                    args.push(format!("{} {}", to_java_type(&f.field_type), f.name));
                }
                let args_str = args.join(", ");

                let fn_name = to_camel_case(&transition.event);

                output.push_str(&format!(
                    "    public {}State {}({}) {{\n",
                    target_state.name, fn_name, args_str
                ));

                output.push_str(&format!("        return new {}State(\n", target_state.name));

                let mut constructor_args = Vec::new();
                for t_field in &target_fields {
                    if source_fields.iter().any(|s| s.name == t_field.name) {
                        constructor_args.push(format!("            this.{}", t_field.name));
                    } else {
                        constructor_args.push(format!("            {}", t_field.name));
                    }
                }

                output.push_str(&constructor_args.join(",\n"));
                output.push_str("\n        );\n    }\n");
            }
            output.push_str("}\n\n");
        }

        output
    }
}
