use super::Generator;
use crate::frontend::ast::{BaseType, TytoProgram, TytoType};

pub struct JavaGenerator;

fn to_camel_case(s: &str) -> String {
    let mut c = s.chars();
    match c.next() {
        None => String::new(),
        Some(f) => f.to_lowercase().collect::<String>() + c.as_str(),
    }
}

fn to_java_type(ty: &TytoType) -> String {
    match ty {
        TytoType::Base(BaseType::String) => "String".to_string(),
        TytoType::Base(BaseType::Int) => "Integer".to_string(),
        TytoType::Base(BaseType::Float) => "Double".to_string(),
        TytoType::Base(BaseType::Bool) => "Boolean".to_string(),
        TytoType::Array(inner) => format!("java.util.List<{}>", to_java_type(inner)),
        TytoType::Optional(inner) => format!("java.util.Optional<{}>", to_java_type(inner)),
    }
}

impl Generator for JavaGenerator {
    fn extension(&self) -> &'static str {
        "java"
    }

    fn generate(&self, program: &TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("// Automatically generated by Tyto\n");
        output.push_str("// Do not edit this file manually.\n\n");

        let state_names: Vec<_> = program
            .states
            .iter()
            .map(|s| format!("{}State", s.name))
            .collect();

        output.push_str(&format!(
            "sealed interface TytoState permits {} {{}}\n\n",
            state_names.join(", ")
        ));

        for state in &program.states {
            let fields = state.all_fields(program);

            let fields_str: Vec<_> = fields
                .iter()
                .map(|f| format!("{} {}", to_java_type(&f.field_type), f.name))
                .collect();

            output.push_str(&format!(
                "record {}State({}) implements TytoState {{\n",
                state.name,
                fields_str.join(", ")
            ));

            let source_fields = state.all_fields(program);

            for transition in &state.transitions {
                let Some(target_state) = program.find_state(&transition.target) else {
                    continue;
                };

                let target_fields = target_state.all_fields(program);

                let new_fields: Vec<_> = target_fields
                    .iter()
                    .filter(|tf| !source_fields.iter().any(|sf| sf.name == tf.name))
                    .collect();

                let args: Vec<_> = new_fields
                    .iter()
                    .map(|f| format!("{} {}", to_java_type(&f.field_type), f.name))
                    .collect();

                let fn_name = to_camel_case(&transition.event);

                output.push_str(&format!(
                    "    public {}State {}({}) {{\n",
                    target_state.name,
                    fn_name,
                    args.join(", ")
                ));

                output.push_str(&format!("        return new {}State(\n", target_state.name));

                let constructor_args: Vec<_> = target_fields
                    .iter()
                    .map(|f| {
                        let prefix = if source_fields.iter().any(|sf| sf.name == f.name) {
                            "this."
                        } else {
                            ""
                        };
                        format!("            {}{}", prefix, f.name)
                    })
                    .collect();

                output.push_str(&constructor_args.join(",\n"));
                output.push_str("\n        );\n    }\n");
            }
            output.push_str("}\n\n");
        }

        output
    }
}
