use super::Generator;
use crate::frontend::ast::TransitionType;

pub struct MermaidGenerator;

impl Generator for MermaidGenerator {
    fn extension(&self) -> &'static str {
        "mmd"
    }

    fn generate(&self, program: &crate::frontend::ast::TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("%% Automatically generated by Tyto\n");
        output.push_str("stateDiagram-v2\n");

        if let Some(first_state) = program.states.first() {
            output.push_str(&format!("    [*] --> {}\n", first_state.name));
        }

        for state in &program.states {
            if state.is_terminal {
                output.push_str(&format!("    {} --> [*]\n", state.name));
                continue;
            }

            for transition in &state.transitions {
                let prefix = match transition.transition_type {
                    TransitionType::Success => "success: ",
                    TransitionType::Recoverable => "recoverable: ",
                    TransitionType::Fatal => "fatal: ",
                    TransitionType::Default => "",
                };

                output.push_str(&format!(
                    "    {} --> {} : {}{}\n",
                    state.name, transition.target, prefix, transition.event
                ));
            }
        }

        output
    }
}
