use super::Generator;
use crate::frontend::ast::{BaseType, TytoProgram, TytoType};

pub struct RustGenerator;

fn to_snake_case(s: &str) -> String {
    let mut snake = String::new();
    for (i, c) in s.char_indices() {
        if i > 0 && c.is_uppercase() {
            snake.push('_');
        }
        snake.extend(c.to_lowercase());
    }
    snake
}

fn to_rust_type(ty: &TytoType) -> String {
    match ty {
        TytoType::Base(BaseType::String) => "String".to_string(),
        TytoType::Base(BaseType::Int) => "i32".to_string(),
        TytoType::Base(BaseType::Float) => "f64".to_string(),
        TytoType::Base(BaseType::Bool) => "bool".to_string(),
        TytoType::Array(inner) => format!("Vec<{}>", to_rust_type(inner)),
        TytoType::Optional(inner) => format!("Option<{}>", to_rust_type(inner)),
    }
}

impl Generator for RustGenerator {
    fn extension(&self) -> &'static str {
        "tyto.rs"
    }

    fn generate(&self, program: &TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("// Automatically generated by Tyto\n");
        output.push_str("// Do not edit this file manually.\n\n");

        for state in &program.states {
            let fields = state.all_fields(program);

            if fields.is_empty() {
                output.push_str(&format!(
                    "#[derive(Debug, Clone)]\npub struct {}State;\n\n",
                    state.name
                ));
            } else {
                output.push_str(&format!(
                    "#[derive(Debug, Clone)]\npub struct {}State {{\n",
                    state.name
                ));
                for field in &fields {
                    output.push_str(&format!(
                        "    pub {}: {},\n",
                        field.name,
                        to_rust_type(&field.field_type)
                    ));
                }
                output.push_str("}\n\n");
            }
        }

        for state in &program.states {
            if state.transitions.is_empty() {
                continue;
            }

            output.push_str(&format!("impl {}State {{\n", state.name));
            let source_fields = state.all_fields(program);

            for transition in &state.transitions {
                let Some(target_state) = program.find_state(&transition.target) else {
                    continue;
                };

                let target_fields = target_state.all_fields(program);

                let new_fields: Vec<_> = target_fields
                    .iter()
                    .filter(|tf| !source_fields.iter().any(|sf| sf.name == tf.name))
                    .collect();

                let args_str = if new_fields.is_empty() {
                    String::new()
                } else {
                    let args: Vec<_> = new_fields
                        .iter()
                        .map(|f| format!("{}: {}", f.name, to_rust_type(&f.field_type)))
                        .collect();
                    format!(", {}", args.join(", "))
                };

                let fn_name = to_snake_case(&transition.event);

                output.push_str(&format!(
                    "    pub fn {}(self{}) -> {}State {{\n",
                    fn_name, args_str, target_state.name
                ));

                if target_fields.is_empty() {
                    output.push_str(&format!("        {}State\n", target_state.name));
                } else {
                    output.push_str(&format!("        {}State {{\n", target_state.name));
                    for field in &target_fields {
                        let value = if source_fields.iter().any(|sf| sf.name == field.name) {
                            format!("self.{}", field.name)
                        } else {
                            field.name.clone()
                        };
                        output.push_str(&format!("            {}: {},\n", field.name, value));
                    }
                    output.push_str("        }\n");
                }
                output.push_str("    }\n");
            }
            output.push_str("}\n\n");
        }

        output
    }
}
