use super::Generator;
use crate::frontend::ast::{BaseType, Field, State, TytoProgram, TytoType};

pub struct RustGenerator;

fn to_snake_case(s: &str) -> String {
    let mut snake = String::new();
    for (i, c) in s.char_indices() {
        if i > 0 && c.is_uppercase() {
            snake.push('_');    
        }
        snake.extend(c.to_lowercase());
    }
    snake
}

fn to_rust_type(ty: &TytoType) -> String {
    match ty {
        TytoType::Base(BaseType::String) => "String".to_string(),
        TytoType::Base(BaseType::Int) => "i32".to_string(),
        TytoType::Base(BaseType::Float) => "f64".to_string(),
        TytoType::Base(BaseType::Bool) => "bool".to_string(),
        TytoType::Array(inner) => format!("Vec<{}>", to_rust_type(inner)),
        TytoType::Optional(inner) => format!("Option<{}>", to_rust_type(inner)),
    }
}

fn get_state_fields(program: &TytoProgram, state: &State) -> Vec<Field> {
    let mut fields = Vec::new();
    if let Some(ctx) = &program.context {
        fields.extend(ctx.fields.clone());
    }
    if let Some(data) = &state.data {
        fields.extend(data.fields.clone());
    }
    fields
}

impl Generator for RustGenerator {
    fn extension(&self) -> &'static str {
        "tyto.rs"
    }

    fn generate(&self, program: &TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("// Automatically generated by Tyto\n");
        output.push_str("// Do not edit this file manually.\n\n");

        for state in &program.states {
            let fields = get_state_fields(program, state);

            if fields.is_empty() {
                output.push_str(&format!(
                    "#[derive(Debug, Clone)]\npub struct {}State;\n\n",
                    state.name
                ));
            } else {
                output.push_str(&format!(
                    "#[derive(Debug, Clone)]\npub struct {}State {{\n",
                    state.name
                ));
                for field in &fields {
                    let rust_type = to_rust_type(&field.field_type);
                    output.push_str(&format!("    pub {}: {},\n", field.name, rust_type));
                }
                output.push_str("}\n\n");
            }
        }

        for state in &program.states {
            if state.transitions.is_empty() {
                continue;
            }

            output.push_str(&format!("impl {}State {{\n", state.name));
            let source_fields = get_state_fields(program, state);

            for transition in &state.transitions {
                let target_state = program
                    .states
                    .iter()
                    .find(|s| s.name == transition.target)
                    .expect("Error: Target state not found.");

                let target_fields = get_state_fields(program, target_state);

                let mut new_fields = Vec::new();
                for t_field in &target_fields {
                    if !source_fields
                        .iter()
                        .any(|s_field| s_field.name == t_field.name)
                    {
                        new_fields.push(t_field.clone());
                    }
                }

                let mut args = Vec::new();
                for f in &new_fields {
                    args.push(format!("{}: {}", f.name, to_rust_type(&f.field_type)));
                }
                let args_str = if args.is_empty() {
                    String::new()
                } else {
                    format!(", {}", args.join(", "))
                };

                let fn_name = to_snake_case(&transition.event);

                output.push_str(&format!(
                    "    pub fn {}(self{}) -> {}State {{\n",
                    fn_name, args_str, target_state.name
                ));

                if target_fields.is_empty() {
                    output.push_str(&format!("        {}State\n", target_state.name));
                } else {
                    output.push_str(&format!("        {}State {{\n", target_state.name));
                    for t_field in &target_fields {
                        if source_fields.iter().any(|s| s.name == t_field.name) {
                            output.push_str(&format!(
                                "            {}: self.{},\n",
                                t_field.name, t_field.name
                            ));
                        } else {
                            output.push_str(&format!(
                                "            {}: {},\n",
                                t_field.name, t_field.name
                            ));
                        }
                    }
                    output.push_str("        }\n");
                }
                output.push_str("    }\n");
            }
            output.push_str("}\n\n");
        }

        output
    }
}
