use crate::frontend::ast::TytoProgram;

pub fn generate_ts(program: &TytoProgram) -> String {
    let mut output = String::new();

    output.push_str("// Automatically generated by Tyto\n");
    output.push_str("// Do not edit this file manually.\n\n");

    let mut state_interfaces = Vec::new();

    for state in &program.states {
        let interface_name = format!("{}State", state.name);
        state_interfaces.push(interface_name.clone());

        output.push_str(&format!("export interface {} {{\n", interface_name));
        output.push_str(&format!("  type: '{}':\n", state.name));

        if let Some(data) = &state.data {
            output.push_str("   data: {\n");
            for field in &data.fields {
                let ts_type = match field.field_type.as_str() {
                    "String" => "string",
                    "u32" | "i32" | "f64" => "number",
                    "bool" => "boolean",
                    _ => "any",
                };
                output.push_str(&format!("  {}: {};\n", field.name, ts_type));
            }
            output.push_str("   };\n");
        }

        output.push_str("}\n\n");
    }

    output.push_str(&format!(
        "export type AppState =\n  | {};\n",
        state_interfaces.join("\n  |")
    ));

    output
}
