use super::Generator;
use crate::frontend::ast::{BaseType, Field, State, TytoProgram, TytoType};

pub struct TypeScriptGenerator;

fn to_ts_type(ty: &TytoType) -> String {
    match ty {
        TytoType::Base(BaseType::String) => "string".to_string(),
        TytoType::Base(BaseType::Int) | TytoType::Base(BaseType::Float) => "number".to_string(),
        TytoType::Base(BaseType::Bool) => "boolean".to_string(),
        TytoType::Array(inner) => format!("{}[]", to_ts_type(inner)),
        TytoType::Optional(inner) => format!("{} | undefined", to_ts_type(inner)),
    }
}

fn get_state_fields(program: &TytoProgram, state: &State) -> Vec<Field> {
    let mut fields = Vec::new();
    if let Some(ctx) = &program.context {
        fields.extend(ctx.fields.clone());
    }
    if let Some(data) = &state.data {
        fields.extend(data.fields.clone());
    }
    fields
}

impl Generator for TypeScriptGenerator {
    fn extension(&self) -> &'static str {
        "tyto.ts"
    }

    fn generate(&self, program: &TytoProgram) -> String {
        let mut output = String::new();

        output.push_str("// Automatically generated by Tyto\n");
        output.push_str("// Do not edit this file manually.\n\n");

        let mut state_interfaces = Vec::new();

        for state in &program.states {
            let interface_name = format!("{}State", state.name);
            state_interfaces.push(interface_name.clone());

            output.push_str(&format!("export interface {} {{\n", interface_name));
            output.push_str(&format!("   readonly type: '{}';\n", state.name));

            let state_fields = get_state_fields(program, state);

            if !state_fields.is_empty() {
                output.push_str("   readonly data: {\n");
                for field in &state_fields {
                    let ts_type = to_ts_type(&field.field_type);
                    output.push_str(&format!("      {}: {};\n", field.name, ts_type));
                }
                output.push_str("   };\n");
            }

            output.push_str("}\n\n");
        }

        output.push_str(&format!(
            "export type AppState =\n  | {};\n\n",
            state_interfaces.join("\n  | ")
        ));

        output.push_str("export class Tyto {\n");

        for state in &program.states {
            let source_fields = get_state_fields(program, state);

            for transition in &state.transitions {
                let target_state = program
                    .states
                    .iter()
                    .find(|s| s.name == transition.target)
                    .expect("Error: Target state not found.");

                let target_fields = get_state_fields(program, target_state);

                let mut new_fields = Vec::new();
                for t_field in &target_fields {
                    if !source_fields
                        .iter()
                        .any(|s_field| s_field.name == t_field.name)
                    {
                        new_fields.push(t_field);
                    }
                }

                let mut payload_arg = String::new();

                if !new_fields.is_empty() {
                    let mut arg_types = Vec::new();
                    for field in &new_fields {
                        let ts_type = to_ts_type(&field.field_type);
                        arg_types.push(format!("{}: {}", field.name, ts_type));
                    }
                    payload_arg = format!(", nextData: {{ {} }}", arg_types.join("; "));
                }

                output.push_str(&format!(
                    "  static transition(state: {}State, event: '{}'{}): {}State;\n",
                    state.name, transition.event, payload_arg, target_state.name
                ));
            }
        }

        output.push_str(
            "  static transition(state: AppState, event: string, nextData?: unknown): AppState {\n",
        );
        output.push_str("    switch (state.type) {\n");

        for state in &program.states {
            if state.transitions.is_empty() {
                continue;
            }

            let source_fields = get_state_fields(program, state);

            output.push_str(&format!("      case '{}':\n", state.name));
            for transition in &state.transitions {
                let target_state = program
                    .states
                    .iter()
                    .find(|s| s.name == transition.target)
                    .unwrap();

                let target_fields = get_state_fields(program, target_state);

                let mut new_fields = Vec::new();
                for t_field in &target_fields {
                    if !source_fields
                        .iter()
                        .any(|s_field| s_field.name == t_field.name)
                    {
                        new_fields.push(t_field);
                    }
                }

                let data_assign = if target_fields.is_empty() {
                    String::new()
                } else if source_fields.is_empty() {
                    format!(", data: nextData as {}State['data']", target_state.name)
                } else if new_fields.is_empty() {
                    format!(
                        ", data: state.data as unknown as {}State['data']",
                        target_state.name
                    )
                } else {
                    format!(
                    ", data: ({{ ...state.data, ...(nextData as object) }} as unknown) as {}State['data']",
                    target_state.name
                )
                };

                output.push_str(&format!(
                    "        if (event === '{}') return {{ type: '{}'{} }};\n",
                    transition.event, target_state.name, data_assign
                ));
            }
            output.push_str("        break;\n");
        }

        output.push_str("    }\n");
        output.push_str(
            "    throw new Error(`Invalid transition: ${event} from state ${state.type}`);\n",
        );
        output.push_str("  }\n");

        output.push_str("}\n");

        output
    }
}
